title: johnny
author: johnny
description: |-
  I am a 19 years old developer with 6 years of experience, numerous projects and commissions under my belt. I provide maximum efficiency, optimization, and orgnization. I strive to be humble and offer quality builds with fair pricing (open to negotations).

  **Payment preference:** USD via PayPal.

  **Note:** This website is a work in progress, I am still collecting all my projects.

gmail: jsfadullo@gmail.com
discord: fadullo
url: "https://fadullo.dev"
baseurl: ""
image: /assets/images/johnny-logo-preview.png
image_width: 512
image_height: 512
link_preview_card: summary
link_preview_description: johnny - developer
default_project_category: other
project_categories:
  - slug: open-source
    title: open-source
  - slug: building
    title: building
  - slug: front-end-scripting
    title: front-end scripting
  - slug: back-end-scripting
    title: back-end scripting
  - slug: other
    title: other
availability_week:
  - day: Mon
    status: online
  - day: Tue
    status: online
  - day: Wed
    status: online
  - day: Thu
    status: online
  - day: Fri
    status: messages
  - day: Sat
    status: messages
  - day: Sun
    status: offline
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
